### ISSUE TITLE
Add Middle East Filter

### ISSUE THREAD

**Issue by newOnahtaN** [newOnahtaN/psaweb#2]
@gmarsillac @abbybilenkin This is an example of a github "issue".

This is the formal way to request changes to the code base, pretty much a centralized to-do list. To get a list of issues, you can click on the "issues" tab above. This issue in particular is to assign Abby to the adding of the middle east filter. 

When a solution has been proposed (namely, a pull request has been opened), it should be linked to in this comment section by the creator of the PR (pull request). When that pull request has been merged in to master (exclusively by someone who did not open the PR), then this issue may be closed, by anyone.

**Comment by cbilenkin** [comment]
Resolved by pull request: https://github.com/newOnahtaN/psaweb/pull/11
